---
- name: "Install sshpass"
  apt:
    name: sshpass
  delegate_to: "{{ middle_address }}"
  become: true

- name: "SSH to target host"
  shell: sshpass -p "{{ target_password }}" ssh "{{ target_user }}"@"{{ target_address }}"
  delegate_to: "{{ middle_address }}"
